#
#drock的Makefile文件
#


CC = gcc

AS = as

LD = ld

RM = rm

CC_FLAGE = -c  -nostdlib -fno-builtin -fno-stack-protector -gstabs+ -Wall -ggdb  -m32

LD_FLAGS = -T tool/kernel.lds -m elf_i386 -nostdlib

AS_FLAGS = -felf -g -F stabs


